### ISSUE TITLE
Datasets Features Names

### ISSUE THREAD

**Issue by msharara1998** [GraphDetec/MGTAB#1]
Hi,
Thank you for your effort on this project. 
I would like to know how can we retrieve the names of the columns (features names) in the dataset, as it is provided as a torch tensor with only numerical values. Similarly, the accounts' human/bot labels are provided as a binary vector, without the account name or IDs.

**Comment by GraphDetec** [comment]
MGTAB is a processed data set for GNNs, similar to Cora, Citeseer, and Pubmed. The features and labels of the account correspond one to one in order. Details of the features are shown in Table 10 of the paper (MGTAB: A Multi-Relational Graph-Based Twitter Account Detection Benchmark [arXiv.2301.01123]). To protect user privacy, account name and IDs are no longer provided.

**Comment by msharara1998** [comment]
Okay I'll check it, thank you.

**Comment by Keepingshtum** [comment]
Hello, I was trying to hunt down "Table 10" but it appears to be missing in the arXiv PDF - I only see tables numbered up to "6" - I did see a table about the "Details of user feature representations" - Table A5, but I'm still not sure where to check what the other features (21-788) are.
