### ISSUE TITLE
Questions about the topics or claims

### ISSUE THREAD

**Issue by hotchilipowder** [GraphDetec/MGTAB#3]
Thank you for offering this project for the stance detection community with social links.
However, I have some questions about the datasets. Could you help me to solve it?

As you said in the introduction section, 
```
Stance detection aims at detecting the user’s stance on a topic or claim. 
```
But in the datasets, I don't find the labels for the topics/claims/events.
I understand that the datasets can be modeled as a node classification task on a  heterogeneous graph.

When I load the label_stances, I can have the label of 0/1/2(neutral/against/support). But I want to know the topic for such labels.
For example, if I have node 0 as 1, node 2 as 1, do they have the same stance on the same topic?
Because the tweets are given with 768-d embeddings, it is hard to extract meaningful topics. 

How can I get the topics/claims for the label of stance?

**Comment by GraphDetec** [comment]
MGTAB contains only one topic: support the UK leaving the EU. 

In the revised manuscript, we will add a description of the topic.

**Comment by hotchilipowder** [comment]
Thank you for your reply. 
Get it!

**Comment by MMMMMz** [comment]
I have the same question. What is your understanding?
