### ISSUE TITLE
Dataset Collection Process

### ISSUE THREAD

**Issue by MMMMMz** [GraphDetec/MGTAB#6]
It's my pleasure to read your paper. I have some questions about the dataset collection process:
How to get the other accounts based on seed accounts?
What are the detailed online events?
What are the relationships between seed accounts and online events?

**Comment by GraphDetec** [comment]
We have chosen 100 seed accounts from users actively participating in the discussion (participating in at least 10 discussions on the topics) regarding Japan’s plan to release nuclear wastewater into the sea. 

These accounts consist of 73 high-influence accounts that have a large number of followers, handpicked by experts. Additionally, 27 accounts were randomly selected to ensure diversity in the sample.

Using the seed account, we conduct BFS-based traversal through follow, follower, mention, and reply relationships to obtain the user network of MGTAB
