### ISSUE TITLE
Stance detection

### ISSUE THREAD

**Issue by MMMMMz** [GraphDetec/MGTAB#8]
Stance detection is generally used to detect the stance of a piece of text.
Is the stance detection label of your data annotation here annotated for all historical tweets of the user as a whole text?

**Comment by GraphDetec** [comment]
MGTAB carries out stance annotation at the user level.

The annotation process of the accounts involved experts thoroughly checking the last 100 tweets of each account. Based on their evaluation, the experts categorized the user’s stance towards the discharged and treated nuclear wastewater in Japan as either supportive, neutral, or opposing.
